### ISSUE TITLE
Error en Ubuntu al intentar cargar planilla

### ISSUE THREAD

**Issue by fgaldeano** [maurooaranda/Automail-HT#1]
Al hacer click en los puntos suspensivos nada sucede en la UI, y en la consola se muetra lo siguiente:

`Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1540, in __call__
    return self.func(*args)
  File "/home/fgaldeano/gitrepo/Automail-HT/src/HTMailsGUI.py", line 254, in get_spreadsheet
    initialdir = self.default_directory,
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1902, in __getattr__
    return getattr(self.tk, attr)
AttributeError: default_directory`

![errorcargandoplanillas](https://user-images.githubusercontent.com/20502136/44763566-3cacde80-ab22-11e8-8548-17298a5eccd9.png)

**Comment by maurooaranda** [comment]
Agregué un fix a master.
Creo haberlo solucionado, a partir del commit a9d2ce2aa82ef17ef41716aa92d192759089d0e3

Podrías probar de nuevo?  Muchas gracias.

**Comment by fgaldeano** [comment]
Ya no tira el error
